// data.js
const haciendas = [
    { codigo: "33", nombre: "Rodeo Grande"},
    { codigo: "879", nombre: "Maria Guadalupe Mejía"},
    { codigo: "993", nombre: "Pansaco"},
    { codigo: "39", nombre: "COOP. MIGUEL ANGEL VASQUEZ"},
    { codigo: "28", nombre: "OJO DE AGUA"},
    { codigo: "91", nombre: "San Felipe"},
    { codigo: "80", nombre: "ERNESTO CENTENO (OBREJUELO)"},
    { codigo: "741", nombre: "Lucy Espinoza Esquivel"},
    { codigo: "14", nombre: "Proyecto Llano El Dorado"},
    { codigo: "11", nombre: "Veracruz"},
    { codigo: "610", nombre: "Carmen Obregón Montiel"},
    { codigo: "990", nombre: "LACHAPA"},
    { codigo: "20", nombre: "San Lucas"},
    { codigo: "60", nombre: "SANTA MARTHA (CAPRIOTTI)"},
    { codigo: "759", nombre: "Jesús María"},
    { codigo: "99", nombre: "Rodolfo Ibarra y/o Dimas Ibarra"},
    { codigo: "908", nombre: "AIDOSA"},
    { codigo: "903", nombre: "Industria Comercial San Martin"},
    { codigo: "55", nombre: "Cristofer Lopez"},
    { codigo: "883", nombre: "Eloy Morales Zambrana"},
    { codigo: "157", nombre: "La Virgen"},
    { codigo: "901", nombre: "Petra Nohemí Pravia Morales"},
    { codigo: "561", nombre: "Alfredo José Siezar Morales"},
    { codigo: "38", nombre: "DAMARIS GONGORA"},
    { codigo: "916", nombre: "Maribel de los Ángeles García Vado"},
    { codigo: "13", nombre: "Las Brisas-2"},
    { codigo: "302", nombre: "La Bendicion"},
    { codigo: "872", nombre: "Pedro Juaquin Ruiz Morales"},
    { codigo: "919", nombre: " Milton Javier Martinez Cruz"},
    { codigo: "185", nombre: "Jose Antonio Salvatierra Bustos"},
    { codigo: "16", nombre: "Sucuya"},
    { codigo: "921", nombre: "Roberto de Jesús Conrado Muñoz."},
    { codigo: "904", nombre: "Alba Nora Argüello Martinez"},
    { codigo: "907", nombre: "Fabrio Perez Salamanca"},
    { codigo: "72", nombre: "Eddy Obregón Pérez"},
    { codigo: "54", nombre: "Rolando Chavarria"},
    { codigo: "983", nombre: "Rancho Peirano"},
    { codigo: "917", nombre: "Bayardo Conrado Traña"},
    { codigo: "17", nombre: "La Esperanza"},
    { codigo: "160", nombre: "Napoleón Zepeda Granja"},
    { codigo: "991", nombre: "Santa Justa"},
    { codigo: "307", nombre: "Katya Espinoza Mendoza."},
    { codigo: "305", nombre: "FRANCISCO ESPINOZA BALTODANO"},
    { codigo: "3", nombre: "El Javillo"},
    { codigo: "303", nombre: "Ena Gongora"},
    { codigo: "982", nombre: "Mario Zavala"},
    { codigo: "440", nombre: "La Avanzada"},
    { codigo: "758", nombre: "Javier Guerra"},
    { codigo: "242", nombre: "Agustin Boiorge Acevedo"},
    { codigo: "9", nombre: "La Pradera"},
    { codigo: "882", nombre: "Venancia del Carmen Ibarra Silva"},
    { codigo: "156", nombre: "PROCARSA"},
    { codigo: "878", nombre: "El Amparo"},
    { codigo: "96", nombre: "Rafael Urtecho Martinez"},
    { codigo: "906", nombre: "María Teodora Fuerte Villarreal"},
    { codigo: "770", nombre: "Santo Domingo"},
    { codigo: "911", nombre: "El Garabato"},
    { codigo: "158", nombre: "Santa Teresa PRCS"},
    { codigo: "12", nombre: "Llano Bonito"},
    { codigo: "420", nombre: "San Ignacio"},
    { codigo: "23", nombre: "SAN FRANCISCO 2 (EVENOR MAYORGA)"},
    { codigo: "31", nombre: "Las Brisas"},
    { codigo: "877", nombre: "Denis Antonio Baldelomar"},
    { codigo: "1", nombre: "Ochomogo"},
    { codigo: "15", nombre: "San Fernandito"},
    { codigo: "196", nombre: "Eduardo Leyva Guevara"},
    { codigo: "611", nombre: "Petrona Hilda Delgado Rojas"},
    { codigo: "750", nombre: "Santa Juana"},
    { codigo: "147", nombre: "El Volcan CSR"},
    { codigo: "190", nombre: "CAEHMSA"},
    { codigo: "304", nombre: "DIEGO MARTINEZ"},
    { codigo: "479", nombre: "Federico Selva Hollman"},
    { codigo: "909", nombre: "Juan Carlos Aviles"},
    { codigo: "306", nombre: "Oscar Danilo Guido Narvaez"},
    { codigo: "760", nombre: "El Rodal"},
    { codigo: "292", nombre: "Edgard Holman"},
    { codigo: "995", nombre: "Rigoberto Conrado"},
    { codigo: "256", nombre: "Dolores"},
    { codigo: "992", nombre: "Mecatepillo"},
    { codigo: "26", nombre: "CRISTINA CASTRO"},
    { codigo: "254", nombre: "Luz Marina Castillo Delgado"},
    { codigo: "27", nombre: "RIO DE JANEIRO"},
    { codigo: "301", nombre: "Miguel Mora"},
    { codigo: "159", nombre: "PROCARSA (CASUR)"},
    { codigo: "5", nombre: "Los Arcos"},
    { codigo: "37", nombre: "COOP. MIGUEL ANGEL VASQUEZ (EL SITIO)"},
    { codigo: "753", nombre: "María Concepción Obregon Montiel"},
    { codigo: "520", nombre: "Cabosa - Magdalena"},
    { codigo: "780", nombre: "Rosario"},
    { codigo: "295", nombre: "Danilo Masís"},
    { codigo: "211", nombre: "Veronica de Los Angees Mendez Alvarado"},
    { codigo: "25", nombre: "Claudio Alberto Reyes Ruiz"},
    { codigo: "740", nombre: "El Porvenir"},
    { codigo: "56", nombre: "Emperatríz Alemán de Pérez"},
    { codigo: "155", nombre: "Michael Healy Lacayo"},
    { codigo: "90", nombre: "María Asunción y/o César Góngora"},
    { codigo: "4", nombre: "Ñocarime"},
    { codigo: "918", nombre: "Medardo Jose Conrado Traña"},
    { codigo: "867", nombre: " Jorge Castro Baltodano"},
    { codigo: "113", nombre: "Franklin Maleaños Urtecho"},
    { codigo: "290", nombre: "La Compañia"},
    { codigo: "29", nombre: "GUADALUPE BARRIOS"},
    { codigo: "915", nombre: "Julio Cesar Conrado Gomez"},
    { codigo: "7", nombre: "Amayo"},
    { codigo: "220", nombre: "El Socorro"},
    { codigo: "40", nombre: "CARLOS MATAMORO"},
    { codigo: "19", nombre: "San Fernando"},
    { codigo: "197", nombre: "Johana de Jesús Solís Andrade"},
    { codigo: "186", nombre: "Alfonzo Rivas"},
    { codigo: "145", nombre: "Las Lajas"},
    { codigo: "614", nombre: "Felipe Alberto Aguilar"},
    { codigo: "410", nombre: "San Fernando Tisma"},
    { codigo: "6", nombre: "Freddy Sovalvarro"},
    { codigo: "914", nombre: "ALDO VANEGAS"},
    { codigo: "752", nombre: "Eduardo José Betanco Pérez"},
    { codigo: "21", nombre: "San Gregorio"},
    { codigo: "494", nombre: "Juan Róger Sáenz Sacasa"},
    { codigo: "97", nombre: "Delfa María Ibarra Paniagua"},
    { codigo: "98", nombre: "Elsa María Ibarra Paniagua"},
    { codigo: "83", nombre: "Vicente Grillo Espinoza"},
    { codigo: "920", nombre: "Luis Amadeo Molina"},
    { codigo: "30", nombre: "San Francisco"},
    { codigo: "8", nombre: "Los Pinos"},
    { codigo: "703", nombre: "Jose Faustino Gazo Espinoza"},
    { codigo: "10", nombre: "El Salitre"},
    { codigo: "905", nombre: "Alberto de Jesús Arguello Martínez"},
    { codigo: "35", nombre: "Noel Jerez (San Francisco)"},
    { codigo: "880", nombre: "Nydia Betanco Pérez"},
    { codigo: "874", nombre: "Jose Luis Padilla"},
    { codigo: "233", nombre: "Gómer Vanegas Rojas"},
    { codigo: "95", nombre: "Dimas y/o Juan Ibarra"},
    { codigo: "199", nombre: "Fernando Castro Baltodano"},
    { codigo: "252", nombre: "CARLOS SIEZAR MORALES"},
    { codigo: "70", nombre: "SILVIO RODRIGUEZ (TERESA)"},
    { codigo: "912", nombre: "EL PLEITO"},
    { codigo: "450", nombre: "San Pablo"},
    { codigo: "36", nombre: "CAR. S.A  (ABEL REYES RIVAS)"},
    { codigo: "299", nombre: "César A Jiménez y/o Francisco Hernández"},
    { codigo: "125", nombre: "José Andrés Pérez Alemán"},
    { codigo: "516", nombre: "Cabosa"},
    { codigo: "53", nombre: "Sebastián Bojorge Acevedo"},
    { codigo: "50", nombre: "SAN FELIX (MORICE)"},
    { codigo: "24", nombre: "NORMA CASTRO"},
    { codigo: "251", nombre: "Eva María Morales Fuerte"},
    { codigo: "300", nombre: "JACKEL JIMENEZ"},
    { codigo: "521", nombre: "BAYRON DE JESUS LEON ZAVALA"},
    { codigo: "32", nombre: "El Sitio"},
    { codigo: "751", nombre: "Johanna Azucena Hurtado Canda"},
    { codigo: "241", nombre: "Ruperto Bojorge Acevedo"},
    { codigo: "184", nombre: "Leyla Román de Arguello"},
    { codigo: "2", nombre: "San Jerónimo"},
    { codigo: "22", nombre: "El Limon"},
    { codigo: "18", nombre: "Santa Fe"},
    { codigo: "148", nombre: "San Ramon"},
    { codigo: "244", nombre: "Misael Villarreal Navarrete"},
    { codigo: "902", nombre: "Guillermo Ibarra Paniagua"},
    { codigo: "871", nombre: "Mayela del Carmen Villareal Esquivel"},
    { codigo: "857", nombre: "Eduardo Castillo Martinez"},
    { codigo: "34", nombre: "La Golondrina"},
    { codigo: "119", nombre: "Salvador Marenco Castillo"},
    { codigo: "146", nombre: "El Volcan"},
    { codigo: "913", nombre: "SAN LUIS"},
    { codigo: "161", nombre: "SAN JOSE (CASUR)"},
    { codigo: "000", nombre: "Hacienda Genérica"},
    { codigo: "910", nombre: "Miramar"},
    // Agrega los demás registros aquí
];

// Función para buscar el nombre de la hacienda por código
function obtenerNombreHacienda(codigo) {
    const hacienda = haciendas.find(h => h.codigo === codigo);
    return hacienda ? hacienda.nombre : null;
}
